#!/bin/bash
# Dump database for databases with a postfix.

# Required Environments
# - HELM_RELEASE_NAME ('-' will be automatically convert into '_')
# - DB_FQDN
# - DB_USERNAME
# - DB_PASSWORD
# - TARGET_DIR
# - OUTPUT_LOG_FILE (optional)

set -eo pipefail

FILENAME=$TARGET_DIR/db-schema.tar.gz
DIRNAME=$HELM_RELEASE_NAME-schema
MYDUMPER_OUTPUT=$TARGET_DIR/$DIRNAME
DB_SUFFIX=$(echo $HELM_RELEASE_NAME | sed "s/-/_/g")

dump_db() {
  rm -rf $MYDUMPER_OUTPUT $FILENAME
  mydumper -h $DB_FQDN -u $DB_USERNAME -p $DB_PASSWORD -o $MYDUMPER_OUTPUT --lock-all-tables -x ".*_$DB_SUFFIX\."
  tar -czvf $FILENAME -C $TARGET_DIR $DIRNAME
  rm -rf $MYDUMPER_OUTPUT
}

if [ -z $OUTPUT_LOG_FILE ]; then
  dump_db
else
  {
    dump_db
  } >> $OUTPUT_LOG_FILE 2>$OUTPUT_LOG_FILE
fi
