#!/bin/bash
# Dump database for databases with a postfix.

# Required Environments
# - DB_NAME_POSTFIX ('-' will be automatically convert into '_')
# - DB_FQDN
# - DB_USERNAME
# - DB_PASSWORD
# - TARGET_DIR
# - OUTPUT_LOG_FILE (optional)

set -eo pipefail

FILENAME=$TARGET_DIR/db-schema.tar.gz
DIRNAME=$DB_NAME_POSTFIX-schema
MYDUMPER_OUTPUT=$TARGET_DIR/$DIRNAME
DB_SUFFIX=$(echo $DB_NAME_POSTFIX | sed "s/-/_/g")

dump_to_pv() {
  rm -rf $MYDUMPER_OUTPUT $FILENAME
  mydumper -h $DB_FQDN -u $DB_USERNAME -p $DB_PASSWORD -o $MYDUMPER_OUTPUT --lock-all-tables -x ".*_$DB_SUFFIX\."
  tar -czvf $FILENAME -C $TARGET_DIR $DIRNAME
  rm -rf $MYDUMPER_OUTPUT
}

if [ -z $OUTPUT_LOG_FILE ]; then
  dump_to_pv
else
  {
    dump_to_pv
  } >> $OUTPUT_LOG_FILE 2>$OUTPUT_LOG_FILE
fi
