#!/bin/bash

set -euo pipefail

export DB_SCRATCH_DIR='/db'

dump_to_s3() {
  mkdir -p "${DB_SCRATCH_DIR}"
  mydumper -h "${DB_FQDN}" -u "${DB_USER_USERNAME}" -p "${DB_USER_PASSWORD}" -o "${DB_SCRATCH_DIR}/${HELM_RELEASE_NAME}-schema" -x ".*-${HELM_RELEASE_NAME}\."
  cd ${DB_SCRATCH_DIR}
  FILENAME=$(date +"%Y-%m-%dT%H-%M-%S%z")-${HELM_RELEASE_NAME}.tar.gz
  tar -czvf "${FILENAME}" "${HELM_RELEASE_NAME}-schema"
  aws s3 cp "${FILENAME}" "${S3_BUCKET_URL}/${HELM_RELEASE_NAME}/${FILENAME}"
}

cleanup() {
  echo "Remove database files"
  rm -rf ${DB_SCRATCH_DIR}
}

dump_to_s3 \ &&
  cleanup \ &&
  echo "Successfully uploaded to ${S3_BUCKET_URL}."
