#!/bin/bash

set -euo pipefail

export DB_SCRATCH_DIR='/db'

dump_to_s3() {
  mydumper -h "${DB_FQDN}" -u "${DB_ROOT_USERNAME}" -p"${DB_ROOT_PASSWORD}" -o "${DB_SCRATCH_DIR}/${HELM_RELEASE_NAME}-schema" -x ".*${HELM_RELEASE_NAME}"
  cd ${DB_SCRATCH_DIR}
  tar -czvf "${S3_FILENAME}" "${HELM_RELEASE_NAME}-schema"
  aws s3 cp "${S3_FILENAME}" "${S3_BUCKET_URL}"
}

cleanup() {
  echo "Remove database files"
  rm -rf ${DB_SCRATCH_DIR}
}

dump_to_s3 \ &&
  cleanup \ &&
  echo "Successfully uploaded to ${S3_BUCKET_URL}."
