#!/bin/bash

set -euo pipefail

export DB_SCRATCH_DIR='/db'

download_from_s3() {
  echo "Downloading database from" $S3_BUCKET_URL
  aws s3 cp "$S3_BUCKET_URL" ${DB_SCRATCH_DIR}/schema.tar.gz && cd ${DB_SCRATCH_DIR}
  echo "Extracting database"
  tar -xvzf schema.tar.gz -C ${DB_SCRATCH_DIR}
  echo 'Removing DEFINER=`\w+`@`%` in views'
  for file in $(ls $DB_SCRATCH_DIR/$HELM_RELEASE_NAME-schema/*.v_*.sql); do
    sed -E -i.bak 's/DEFINER=`\w+`@`%`//g' $file
    rm $DB_SCRATCH_DIR/$HELM_RELEASE_NAME-schema/*.v_*.sql.bak
  done
}

restore_schemas() {
  myloader -h "$DB_FQDN" -u "$DB_USER_USERNAME" -p "$DB_USER_PASSWORD" -o -d ${DB_SCRATCH_DIR}/$HELM_RELEASE_NAME-schema || true
}

cleanup() {
  echo "Remove database files"
  rm -rf ${DB_SCRATCH_DIR}
}

echo "Restoring DB from $S3_BUCKET_URL to $HELM_RELEASE_NAME" \ &&
  download_from_s3 \ &&
  restore_schemas \ &&
  cleanup \ &&
  echo "All good to go."
